;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        org-delete-char
        org-self-insert-command
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/mark-more-like-this-extended
        hydra-multiple-cursors/mc/mark-next-like-this
        ))
